name: SSR deploy
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      APP_NAME: aggregator
      TARGET: ${{ format('/home/{0}/superhero-ui', secrets.SSR_STAGE_USER) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm i
      - run: npm test
      - run: NODE_ENV=production npm run ssr:build

      - uses: rlespinasse/github-slug-action@v3.x

      - name: Deploy to stage
        uses: easingthemes/ssh-deploy@v2.1.5
        if: github.event_name == 'push'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSR_STAGE_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSR_STAGE_HOST }}
          REMOTE_USER: ${{ secrets.SSR_STAGE_USER }}
          SOURCE: .
          TARGET: ${{ env.TARGET }}
          EXCLUDE: '/.git/, /node_modules/'

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        if: github.event_name == 'push'
        env:
          NODE_ENV: production
          HOME: /home/${{ secrets.SSR_STAGE_USER }}
          NVM_DIR: /home/${{ secrets.SSR_STAGE_USER }}/.nvm
          TARGET: ${{ env.TARGET }}
        with:
          hosts: '${{ secrets.SSR_STAGE_USER }}@${{ secrets.SSR_STAGE_HOST }}'
          privateKey: ${{ secrets.SSR_STAGE_PRIVATE_KEY }}
          debug: true
          command: |
            source ${{ env.NVM_DIR }}/nvm.sh || exit 1
            cd ${{ env.TARGET }} || exit 1
            nvm install 14 --latest-npm --no-progress --default || exit 1
            npm i || exit 1
            killall node
            setsid nohup npm run ssr:start </dev/null &2>log.log &
            disown

      - uses: unsplash/comment-on-pr@85a56be792d927ac4bfa2f4326607d38e80e6e60
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOST: ${{ secrets.SSR_STAGE_HOST }}
        with:
          msg: Deployed to [${{ env.HOST }}](https://${{ env.HOST }}), [bundle report](https://${{ env.HOST }}/report.html)
          check_for_duplicate_msg: true

